### ISSUE TITLE
Unable to make authenticated request from asyncData

### ISSUE THREAD

**Issue by calvinmuller** [feathersjs-ecosystem/feathers-vuex#350]
### Steps to reproduce
If I navigate from the login route to the index route - all is good.
If I refresh pages on index route - I get 
```
(node:39141) UnhandledPromiseRejectionWarning: NotAuthenticated: Not authenticated
    at new NotAuthenticated (/Users/sites/feathers/node_modules/@feathersjs/errors/lib/index.js:93:17)
```
Cookie is stored in `feathers-jwt` with value `eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE1NzM1NDAwNjksImV4cCI6MTU3MzYyNjQ2OSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiMSIsImp0aSI6ImQ2NTVhZGY2LWExOWUtNGM4ZC1hNzZlLWU4NmIzNDYzMzQ2YyJ9.QbB71CG0XGrU_KlUEq-vPgiNdO9om9ASmfesnidZuW4`

Not too sure if i'm missing something or if this is not possible in my current setup, if you could point me to an article/docs on how to achieve this. Thanks!

`store/index.js`
```
import Vuex from 'vuex'
import Vue from 'vue'
import feathersClient, {BaseModel, makeServicePlugin} from '../feathers-client'
import feathersVuex, { initAuth } from 'feathers-vuex'
const { makeAuthPlugin, FeathersVuex } = feathersVuex(feathersClient);

class User extends BaseModel {
  // required
  constructor (data, options) {
    super(data, options)
  }
  // required
  static modelName = 'User'
}

const usersPlugin = makeServicePlugin({
  Model: User,
  service: feathersClient.service('users')
})

const createStore = () => {
  return new Vuex.Store({
    state: {},
    mutations: {
      increment (state) {
        state.counter++
      }
    },
    actions: {
      nuxtServerInit ({ commit, dispatch, state }, { req }) {
       initAuth({
         req,
         commit,
         module: 'auth'
       }).then(result => {})
      }
    },
    plugins: [
      usersPlugin,
      makeAuthPlugin({
        state: {
          publicPages: [
            'login',
            'signup'
          ]
        }
      })
    ]
  })
};

export default createStore
```
`feathers-client.js`
```
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import auth from '@feathersjs/authentication-client'

import io from 'socket.io-client'
// import feathersVuex from 'feathers-vuex'
import { CookieStorage } from 'cookie-storage'
import feathersVuex from "feathers-vuex";

const storage = new CookieStorage();
const socket = io('http://localhost:3000', {transports: ['websocket']})

const feathersClient = feathers()
  .configure(socketio(socket))
  .configure(auth({ storage }));

export default feathersClient

// // Setting up feathers-vuex
const { makeAuthPlugin, makeServicePlugin, models, BaseModel} = feathersVuex(
  feathersClient,
  {
    serverAlias: 'api', // optional for working with multiple APIs (this is the default value)
    idField: 'id', // Must match the id field in your database table/collection
    whitelist: ['$regex', '$options']
  }
)

export { makeAuthPlugin, makeServicePlugin, models, BaseModel }
```
`index.vue`
```
<script>
    import {models} from "../feathers-client";

    export default {
        middleware: ['auth'],
        async asyncData() {
            const {data} = await models.api.User.find();
            return {
                users: data
            }
        },
        methods: {
            handleSelect(key, keyPath) {
            }
        },
        data() {
            return {
            }
        }
    }
</script>
```
### Expected behavior
I'd expect when loading on index route to retrieve users data

### Actual behavior
```
(node:39141) UnhandledPromiseRejectionWarning: NotAuthenticated: Not authenticated
    at new NotAuthenticated (/Users/calvinmuller/iStreet/Sites/pacs/node_modules/@feathersjs/errors/lib/index.js:93:17)
    at Object.convert (/Users/calvinmuller/iStreet/Sites/pacs/node_modules/@feathersjs/errors/lib/index.js:239:7)
    at Socket.<anonymous> (/Users/calvinmuller/iStreet/Sites/pacs/node_modules/@feathersjs/transport-commons/lib/client.js:67:34)
    at Socket.module.exports../node_modules/socket.io-client/lib/socket.js.Socket.onack (node_modules/socket.io-client/lib/socket.js:319:0)
    at Socket.module.exports../node_modules/socket.io-client/lib/socket.js.Socket.onpacket (node_modules/socket.io-client/lib/socket.js:244:0)
    at Manager.<anonymous> (/Users/calvinmuller/iStreet/Sites/pacs/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/Users/calvinmuller/iStreet/Sites/pacs/node_modules/component-emitter/index.js:133:20)

```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
{
    "@feathersjs/adapter-commons": "^4.3.11",
    "@feathersjs/authentication": "^4.3.11",
    "@feathersjs/authentication-client": "^4.3.11",
    "@feathersjs/authentication-local": "^4.3.11",
    "@feathersjs/authentication-oauth": "^4.3.11",
    "@feathersjs/configuration": "^4.3.11",
    "@feathersjs/errors": "^4.3.11",
    "@feathersjs/express": "^4.3.11",
    "@feathersjs/feathers": "^4.3.11",
    "@feathersjs/rest-client": "^4.3.11",
    "@feathersjs/socketio": "^4.3.11",
    "@feathersjs/socketio-client": "^4.3.11",
    "@feathersjs/transport-commons": "^4.3.11",
    "@nuxtjs/auth": "^4.8.4",
    "@nuxtjs/axios": "^5.8.0",
    "compression": "^1.7.4",
    "cookie-storage": "^5.0.3",
    "cors": "^2.8.5",
    "cross-env": "^5.2.0",
    "element-ui": "^2.4.11",
    "feathers-hooks-common": "^4.20.7",
    "feathers-sequelize": "^6.1.0",
    "feathers-vuex": "^2.2.4",
    "helmet": "^3.21.2",
    "mysql2": "^2.0.0",
    "nuxt": "^2.0.0",
    "sequelize": "^5.21.2",
    "serve-favicon": "^2.5.0",
    "socket.io-client": "^2.3.0",
    "winston": "^3.2.1"
  }
```

**Comment by J3m5** [comment]
Hi,
why are you using cookie-storage?
Could you try with localStorage? 
It seems that the feathers-client doesn't send the jwt in the request.

**Comment by calvinmuller** [comment]
Hey there, unfortunately localStorage is not something that exists on SSR. I would think it would strip the access token out of the request cookies and push it through to feathers client.

**Comment by J3m5** [comment]
Ok, so look at the network tabs in your developer tools to see if the  jwt is sent in the "Authorization" header.
If it's not you could add it manually in the before hooks of the local auth service.

**Comment by marshallswain** [comment]
CookieStorage is recommended for SSR setups where you want to deliver "authenticated data" to the client on page load.  @calvinmuller, you probably need to be sure to call `feathersClient.authenticate` before you make any server requests.

**Comment by nakedgun** [comment]
@calvinmuller - exact same issue I was facing yesterday. I documented a solution for making authenticated requests in SSR setups in this case: #351.

**Comment by marshallswain** [comment]
I'm closing this now that we have a full Nuxt example in the docs.  Thanks!
